### ISSUE TITLE
Inconsistent Python version requirements. Unit Tests errors state that Python 3.6+ is required, whereas Readme says only Python 2.7, 3.4, or 3.5 are supported

### ISSUE THREAD

**Issue by ltfschoen** [ethereum/sharding#52]
My system: macOS Sierra 10.12.6

In the ["Environment" section of the Sharding Specification Readme](https://github.com/ethereum/sharding#environment) it provides a link to the Pyethereum Developer Notes. 
In the ["Installation" section of the Pyethereum Developer Notes](https://github.com/ethereum/pyethereum/wiki/Developer-Notes#installation) it states that `only Python versions 2.7, 3.4, or 3.5 are supported`
Since my host machine is macOS I switched to the latest supported version of Python that it mentions (i.e. Python 3.5) using [pyenv](https://github.com/pyenv/pyenv)

```shell
pyenv install 3.5.0; pyenv global 3.5.0; pyenv versions;
```

But when I run the Unit Tests with `pytest sharding/tests/`, it gives me the exception that I need Python 3.6+ `Exception: Requires python3.6+`, as follows:

```shell
$ pytest sharding/tests/
================================================== test session starts ==================================================
platform darwin -- Python 3.5.0, pytest-3.3.1, py-1.5.2, pluggy-0.6.0
rootdir: /Users/Ls/code/blockchain/clones/sharding, inifile:
plugins: cov-2.5.1, catchlog-1.2.2, timeout-1.0.0
collected 1 item / 11 errors                                                                                            

======================================================== ERRORS =========================================================
___________________________________ ERROR collecting sharding/tests/test_collator.py ____________________________________
sharding/tests/test_collator.py:11: in <module>
    from sharding import collator
sharding/collator.py:9: in <module>
    from sharding import state_transition
sharding/state_transition.py:13: in <module>
    from sharding.validator_manager_utils import call_valmgr
sharding/validator_manager_utils.py:3: in <module>
    from viper import compiler
<frozen importlib._bootstrap>:969: in _find_and_load
    ???
<frozen importlib._bootstrap>:958: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:664: in _load_unlocked
    ???
<frozen importlib._bootstrap>:634: in _load_backward_compatible
    ???
/Users/Ls/.pyenv/versions/3.5.0/lib/python3.5/site-packages/viper-0.0.2-py3.5.egg/viper/__init__.py:5: in <module>
    ???
E   Exception: Requires python3.6+
__________________________________ ERROR collecting sharding/tests/test_main_chain.py ___________________________________
sharding/tests/test_main_chain.py:7: in <module>
    from sharding.tools import tester
sharding/tools/__init__.py:1: in <module>
    from sharding.tools import tester
sharding/tools/tester.py:31: in <module>
    from ethereum.tools._solidity import get_solidity
/Users/Ls/.pyenv/versions/3.5.0/lib/python3.5/site-packages/ethereum-2.1.0-py3.5.egg/ethereum/tools/__init__.py:1: in <module>
    from ethereum.tools import keys, new_statetest_utils, testutils, tester, _solidity
/Users/Ls/.pyenv/versions/3.5.0/lib/python3.5/site-packages/ethereum-2.1.0-py3.5.egg/ethereum/tools/tester.py:47: in <module>
    from viper import compiler
<frozen importlib._bootstrap>:969: in _find_and_load
    ???
<frozen importlib._bootstrap>:958: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:664: in _load_unlocked
    ???
<frozen importlib._bootstrap>:634: in _load_backward_compatible
    ???
/Users/Ls/.pyenv/versions/3.5.0/lib/python3.5/site-packages/viper-0.0.2-py3.5.egg/viper/__init__.py:5: in <module>
    ???
E   Exception: Requires python3.6+
---------------------------------------------------- Captured stderr ----------------------------------------------------

Failed to import bitcoin. This is not a fatal error but does
mean that you will not be able to determine the address from
your wallet file.
__________________________ ERROR collecting sharding/tests/test_receipt_consuming_tx_utils.py ___________________________
sharding/tests/test_receipt_consuming_tx_utils.py:8: in <module>
    from sharding.tools import tester as t
sharding/tools/__init__.py:1: in <module>
    from sharding.tools import tester
sharding/tools/tester.py:33: in <module>
    from sharding.main_chain import MainChain
sharding/main_chain.py:23: in <module>
    from sharding.shard_chain import ShardChain
sharding/shard_chain.py:25: in <module>
    from sharding.collator import apply_collation
sharding/collator.py:9: in <module>
    from sharding import state_transition
sharding/state_transition.py:13: in <module>
    from sharding.validator_manager_utils import call_valmgr
sharding/validator_manager_utils.py:3: in <module>
    from viper import compiler
<frozen importlib._bootstrap>:969: in _find_and_load
    ???
<frozen importlib._bootstrap>:958: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:664: in _load_unlocked
    ???
<frozen importlib._bootstrap>:634: in _load_backward_compatible
    ???
/Users/Ls/.pyenv/versions/3.5.0/lib/python3.5/site-packages/viper-0.0.2-py3.5.egg/viper/__init__.py:5: in <module>
    ???
E   Exception: Requires python3.6+
__________________________________ ERROR collecting sharding/tests/test_shard_chain.py __________________________________
sharding/tests/test_shard_chain.py:12: in <module>
    from sharding.tools import tester
sharding/tools/__init__.py:1: in <module>
    from sharding.tools import tester
sharding/tools/tester.py:33: in <module>
    from sharding.main_chain import MainChain
sharding/main_chain.py:23: in <module>
    from sharding.shard_chain import ShardChain
sharding/shard_chain.py:25: in <module>
    from sharding.collator import apply_collation
sharding/collator.py:9: in <module>
    from sharding import state_transition
sharding/state_transition.py:13: in <module>
    from sharding.validator_manager_utils import call_valmgr
sharding/validator_manager_utils.py:3: in <module>
    from viper import compiler
<frozen importlib._bootstrap>:969: in _find_and_load
    ???
<frozen importlib._bootstrap>:958: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:664: in _load_unlocked
    ???
<frozen importlib._bootstrap>:634: in _load_backward_compatible
    ???
/Users/Ls/.pyenv/versions/3.5.0/lib/python3.5/site-packages/viper-0.0.2-py3.5.egg/viper/__init__.py:5: in <module>
    ???
E   Exception: Requires python3.6+
_______________________________ ERROR collecting sharding/tests/test_state_transition.py ________________________________
sharding/tests/test_state_transition.py:19: in <module>
    from sharding import state_transition
sharding/state_transition.py:13: in <module>
    from sharding.validator_manager_utils import call_valmgr
sharding/validator_manager_utils.py:3: in <module>
    from viper import compiler
<frozen importlib._bootstrap>:969: in _find_and_load
    ???
<frozen importlib._bootstrap>:958: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:664: in _load_unlocked
    ???
<frozen importlib._bootstrap>:634: in _load_backward_compatible
    ???
/Users/Ls/.pyenv/versions/3.5.0/lib/python3.5/site-packages/viper-0.0.2-py3.5.egg/viper/__init__.py:5: in <module>
    ???
E   Exception: Requires python3.6+
______________________________ ERROR collecting sharding/tests/test_stateless_collator.py _______________________________
sharding/tests/test_stateless_collator.py:8: in <module>
    from sharding import collator
sharding/collator.py:9: in <module>
    from sharding import state_transition
sharding/state_transition.py:13: in <module>
    from sharding.validator_manager_utils import call_valmgr
sharding/validator_manager_utils.py:3: in <module>
    from viper import compiler
<frozen importlib._bootstrap>:969: in _find_and_load
    ???
<frozen importlib._bootstrap>:958: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:664: in _load_unlocked
    ???
<frozen importlib._bootstrap>:634: in _load_backward_compatible
    ???
/Users/Ls/.pyenv/versions/3.5.0/lib/python3.5/site-packages/viper-0.0.2-py3.5.egg/viper/__init__.py:5: in <module>
    ???
E   Exception: Requires python3.6+
____________________________________ ERROR collecting sharding/tests/test_tester.py _____________________________________
sharding/tests/test_tester.py:8: in <module>
    from sharding.tools import tester
sharding/tools/__init__.py:1: in <module>
    from sharding.tools import tester
sharding/tools/tester.py:33: in <module>
    from sharding.main_chain import MainChain
sharding/main_chain.py:23: in <module>
    from sharding.shard_chain import ShardChain
sharding/shard_chain.py:25: in <module>
    from sharding.collator import apply_collation
sharding/collator.py:9: in <module>
    from sharding import state_transition
sharding/state_transition.py:13: in <module>
    from sharding.validator_manager_utils import call_valmgr
sharding/validator_manager_utils.py:3: in <module>
    from viper import compiler
<frozen importlib._bootstrap>:969: in _find_and_load
    ???
<frozen importlib._bootstrap>:958: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:664: in _load_unlocked
    ???
<frozen importlib._bootstrap>:634: in _load_backward_compatible
    ???
/Users/Ls/.pyenv/versions/3.5.0/lib/python3.5/site-packages/viper-0.0.2-py3.5.egg/viper/__init__.py:5: in <module>
    ???
E   Exception: Requires python3.6+
______________________________ ERROR collecting sharding/tests/test_used_receipt_store.py _______________________________
sharding/tests/test_used_receipt_store.py:3: in <module>
    from sharding.tools import tester as t
sharding/tools/__init__.py:1: in <module>
    from sharding.tools import tester
sharding/tools/tester.py:33: in <module>
    from sharding.main_chain import MainChain
sharding/main_chain.py:23: in <module>
    from sharding.shard_chain import ShardChain
sharding/shard_chain.py:25: in <module>
    from sharding.collator import apply_collation
sharding/collator.py:9: in <module>
    from sharding import state_transition
sharding/state_transition.py:13: in <module>
    from sharding.validator_manager_utils import call_valmgr
sharding/validator_manager_utils.py:3: in <module>
    from viper import compiler
<frozen importlib._bootstrap>:969: in _find_and_load
    ???
<frozen importlib._bootstrap>:958: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:664: in _load_unlocked
    ???
<frozen importlib._bootstrap>:634: in _load_backward_compatible
    ???
/Users/Ls/.pyenv/versions/3.5.0/lib/python3.5/site-packages/viper-0.0.2-py3.5.egg/viper/__init__.py:5: in <module>
    ???
E   Exception: Requires python3.6+
___________________________ ERROR collecting sharding/tests/test_used_receipt_store_utils.py ____________________________
sharding/tests/test_used_receipt_store_utils.py:1: in <module>
    from sharding.tools import tester as t
sharding/tools/__init__.py:1: in <module>
    from sharding.tools import tester
sharding/tools/tester.py:33: in <module>
    from sharding.main_chain import MainChain
sharding/main_chain.py:23: in <module>
    from sharding.shard_chain import ShardChain
sharding/shard_chain.py:25: in <module>
    from sharding.collator import apply_collation
sharding/collator.py:9: in <module>
    from sharding import state_transition
sharding/state_transition.py:13: in <module>
    from sharding.validator_manager_utils import call_valmgr
sharding/validator_manager_utils.py:3: in <module>
    from viper import compiler
<frozen importlib._bootstrap>:969: in _find_and_load
    ???
<frozen importlib._bootstrap>:958: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:664: in _load_unlocked
    ???
<frozen importlib._bootstrap>:634: in _load_backward_compatible
    ???
/Users/Ls/.pyenv/versions/3.5.0/lib/python3.5/site-packages/viper-0.0.2-py3.5.egg/viper/__init__.py:5: in <module>
    ???
E   Exception: Requires python3.6+
_______________________________ ERROR collecting sharding/tests/test_validator_manager.py _______________________________
sharding/tests/test_validator_manager.py:7: in <module>
    from sharding.tools import tester as t
sharding/tools/__init__.py:1: in <module>
    from sharding.tools import tester
sharding/tools/tester.py:33: in <module>
    from sharding.main_chain import MainChain
sharding/main_chain.py:23: in <module>
    from sharding.shard_chain import ShardChain
sharding/shard_chain.py:25: in <module>
    from sharding.collator import apply_collation
sharding/collator.py:9: in <module>
    from sharding import state_transition
sharding/state_transition.py:13: in <module>
    from sharding.validator_manager_utils import call_valmgr
sharding/validator_manager_utils.py:3: in <module>
    from viper import compiler
<frozen importlib._bootstrap>:969: in _find_and_load
    ???
<frozen importlib._bootstrap>:958: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:664: in _load_unlocked
    ???
<frozen importlib._bootstrap>:634: in _load_backward_compatible
    ???
/Users/Ls/.pyenv/versions/3.5.0/lib/python3.5/site-packages/viper-0.0.2-py3.5.egg/viper/__init__.py:5: in <module>
    ???
E   Exception: Requires python3.6+
____________________________ ERROR collecting sharding/tests/test_validator_manager_utils.py ____________________________
sharding/tests/test_validator_manager_utils.py:6: in <module>
    from sharding.tools import tester as t
sharding/tools/__init__.py:1: in <module>
    from sharding.tools import tester
sharding/tools/tester.py:33: in <module>
    from sharding.main_chain import MainChain
sharding/main_chain.py:23: in <module>
    from sharding.shard_chain import ShardChain
sharding/shard_chain.py:25: in <module>
    from sharding.collator import apply_collation
sharding/collator.py:9: in <module>
    from sharding import state_transition
sharding/state_transition.py:13: in <module>
    from sharding.validator_manager_utils import call_valmgr
sharding/validator_manager_utils.py:3: in <module>
    from viper import compiler
<frozen importlib._bootstrap>:969: in _find_and_load
    ???
<frozen importlib._bootstrap>:958: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:664: in _load_unlocked
    ???
<frozen importlib._bootstrap>:634: in _load_backward_compatible
    ???
/Users/Ls/.pyenv/versions/3.5.0/lib/python3.5/site-packages/viper-0.0.2-py3.5.egg/viper/__init__.py:5: in <module>
    ???
E   Exception: Requires python3.6+
=================================================== warnings summary ====================================================
None
  pytest-catchlog plugin has been merged into the core, please remove it from your requirements.

-- Docs: http://doc.pytest.org/en/latest/warnings.html
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 11 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================= 1 warnings, 11 error in 3.51 seconds ==========================================
```

So to run the Unit Tests I switch to the latest version of Python (even though the link in the Readme mentions that only specific versions are supported)

```shell
pyenv install 3.6.4rc1; pyenv global 3.6.4rc1
```

Then I try to install the relevant dependencies for the Python 3.6+ version, with guidance from the Readme, but I get the following error (with either Python 3.6.3 or 3.6.4rc1):

```
$ python setup.py install
...
error: ethereum 2.3.0 is installed but ethereum==2.1.0 is required by {'viper'}
```

And when I run the Unit Tests they appear with other errors as follows (but without any Python version error anymore)

```shell
$ pytest sharding/tests/
================================================== test session starts ==================================================
platform darwin -- Python 3.6.3, pytest-3.2.5, py-1.5.2, pluggy-0.4.0
rootdir: /Users/Ls/code/blockchain/clones/sharding, inifile:
plugins: xdist-1.20.1, pythonpath-0.7.1, mock-1.6.3, forked-0.2, hypothesis-3.38.5, flaky-3.4.0
collected 1 item / 11 errors                                                                                             

===Flaky Test Report===


===End Flaky Test Report===
======================================================== ERRORS =========================================================
___________________________________ ERROR collecting sharding/tests/test_collator.py ____________________________________
ImportError while importing test module '/Users/Ls/code/blockchain/clones/sharding/sharding/tests/test_collator.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
sharding/tests/test_collator.py:5: in <module>
    from ethereum.transaction_queue import TransactionQueue
E   ModuleNotFoundError: No module named 'ethereum.transaction_queue'
__________________________________ ERROR collecting sharding/tests/test_main_chain.py ___________________________________
ImportError while importing test module '/Users/Ls/code/blockchain/clones/sharding/sharding/tests/test_main_chain.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
sharding/tests/test_main_chain.py:7: in <module>
    from sharding.tools import tester
sharding/tools/__init__.py:1: in <module>
    from sharding.tools import tester
sharding/tools/tester.py:6: in <module>
    from ethereum.utils import (
E   ImportError: cannot import name 'checksum_encode'
__________________________ ERROR collecting sharding/tests/test_receipt_consuming_tx_utils.py ___________________________
ImportError while importing test module '/Users/Ls/code/blockchain/clones/sharding/sharding/tests/test_receipt_consuming_tx_utils.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
sharding/tests/test_receipt_consuming_tx_utils.py:8: in <module>
    from sharding.tools import tester as t
sharding/tools/__init__.py:1: in <module>
    from sharding.tools import tester
sharding/tools/tester.py:6: in <module>
    from ethereum.utils import (
E   ImportError: cannot import name 'checksum_encode'
__________________________________ ERROR collecting sharding/tests/test_shard_chain.py __________________________________
ImportError while importing test module '/Users/Ls/code/blockchain/clones/sharding/sharding/tests/test_shard_chain.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
sharding/tests/test_shard_chain.py:6: in <module>
    from ethereum.transaction_queue import TransactionQueue
E   ModuleNotFoundError: No module named 'ethereum.transaction_queue'
_______________________________ ERROR collecting sharding/tests/test_state_transition.py ________________________________
ImportError while importing test module '/Users/Ls/code/blockchain/clones/sharding/sharding/tests/test_state_transition.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
sharding/tests/test_state_transition.py:4: in <module>
    from ethereum.state import State
E   ModuleNotFoundError: No module named 'ethereum.state'
______________________________ ERROR collecting sharding/tests/test_stateless_collator.py _______________________________
ImportError while importing test module '/Users/Ls/code/blockchain/clones/sharding/sharding/tests/test_stateless_collator.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
sharding/tests/test_stateless_collator.py:6: in <module>
    from ethereum.transaction_queue import TransactionQueue
E   ModuleNotFoundError: No module named 'ethereum.transaction_queue'
____________________________________ ERROR collecting sharding/tests/test_tester.py _____________________________________
ImportError while importing test module '/Users/Ls/code/blockchain/clones/sharding/sharding/tests/test_tester.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
sharding/tests/test_tester.py:8: in <module>
    from sharding.tools import tester
sharding/tools/__init__.py:1: in <module>
    from sharding.tools import tester
sharding/tools/tester.py:6: in <module>
    from ethereum.utils import (
E   ImportError: cannot import name 'checksum_encode'
______________________________ ERROR collecting sharding/tests/test_used_receipt_store.py _______________________________
ImportError while importing test module '/Users/Ls/code/blockchain/clones/sharding/sharding/tests/test_used_receipt_store.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
sharding/tests/test_used_receipt_store.py:3: in <module>
    from sharding.tools import tester as t
sharding/tools/__init__.py:1: in <module>
    from sharding.tools import tester
sharding/tools/tester.py:6: in <module>
    from ethereum.utils import (
E   ImportError: cannot import name 'checksum_encode'
___________________________ ERROR collecting sharding/tests/test_used_receipt_store_utils.py ____________________________
ImportError while importing test module '/Users/Ls/code/blockchain/clones/sharding/sharding/tests/test_used_receipt_store_utils.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
sharding/tests/test_used_receipt_store_utils.py:1: in <module>
    from sharding.tools import tester as t
sharding/tools/__init__.py:1: in <module>
    from sharding.tools import tester
sharding/tools/tester.py:6: in <module>
    from ethereum.utils import (
E   ImportError: cannot import name 'checksum_encode'
_______________________________ ERROR collecting sharding/tests/test_validator_manager.py _______________________________
ImportError while importing test module '/Users/Ls/code/blockchain/clones/sharding/sharding/tests/test_validator_manager.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
sharding/tests/test_validator_manager.py:7: in <module>
    from sharding.tools import tester as t
sharding/tools/__init__.py:1: in <module>
    from sharding.tools import tester
sharding/tools/tester.py:6: in <module>
    from ethereum.utils import (
E   ImportError: cannot import name 'checksum_encode'
____________________________ ERROR collecting sharding/tests/test_validator_manager_utils.py ____________________________
ImportError while importing test module '/Users/Ls/code/blockchain/clones/sharding/sharding/tests/test_validator_manager_utils.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
sharding/tests/test_validator_manager_utils.py:6: in <module>
    from sharding.tools import tester as t
sharding/tools/__init__.py:1: in <module>
    from sharding.tools import tester
sharding/tools/tester.py:6: in <module>
    from ethereum.utils import (
E   ImportError: cannot import name 'checksum_encode'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 11 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=============================================== 11 error in 1.22 seconds ================================================
```

**Comment by mhchia** [comment]
Thank you for pointing out this issue.
We should change the `README.md` in this case.
Since viper requires python3.6, and pyethereum works fine with python3.6
So you should use python3.6 instead.

**Comment by ltfschoen** [comment]
So far I've fixed the error `error: ethereum 2.3.0 is installed but ethereum==2.1.0 is required by {'viper'}` by simply uninstalling the latest 2.3.0 version installed of [Ethereum from Python Package Index (PyPI)](https://pypi.python.org/pypi/ethereum/2.3.0), and then reinstalling the version 2.1.0 that is supported by Viper

```
python -m pip uninstall ethereum==2.3.0;
python -m pip install ethereum==2.1.0
```

**Comment by jamesray1** [comment]
I'll change the pyethereum wiki as well then since it says "Only Python versions 2.7, 3.4, or 3.5 are supported."

**Comment by hwwhww** [comment]
outdated
